/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransaksiRouteImport } from './routes/transaksi'
import { Route as ReminderDemoRouteImport } from './routes/reminder-demo'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgramKerjaRouteImport } from './routes/program-kerja'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PengumumanRouteImport } from './routes/pengumuman'
import { Route as OrganisasiSayaRouteImport } from './routes/organisasi-saya'
import { Route as NotifikasiRouteImport } from './routes/notifikasi'
import { Route as MengapaPatunginRouteImport } from './routes/mengapa-patungin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as KonfirmasiBayarRouteImport } from './routes/konfirmasi-bayar'
import { Route as JoinGrupRouteImport } from './routes/join-grup'
import { Route as IurankuRouteImport } from './routes/iuranku'
import { Route as IuranOrganisasiRouteImport } from './routes/iuran-organisasi'
import { Route as InfoGrupRouteImport } from './routes/info-grup'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EventSayaRouteImport } from './routes/event-saya'
import { Route as AnggotaRouteImport } from './routes/anggota'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramKerjaBuatRouteImport } from './routes/program-kerja_.buat'
import { Route as ProgramKerjaProgIdRouteImport } from './routes/program-kerja_.$progId'
import { Route as LaporanCatIdRouteImport } from './routes/laporan_.$catId'
import { Route as IuranOrganisasiIuranIdRouteImport } from './routes/iuran-organisasi_.$iuranId'
import { Route as EventEventIdRouteImport } from './routes/event_.$eventId'

const TransaksiRoute = TransaksiRouteImport.update({
  id: '/transaksi',
  path: '/transaksi',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderDemoRoute = ReminderDemoRouteImport.update({
  id: '/reminder-demo',
  path: '/reminder-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramKerjaRoute = ProgramKerjaRouteImport.update({
  id: '/program-kerja',
  path: '/program-kerja',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PengumumanRoute = PengumumanRouteImport.update({
  id: '/pengumuman',
  path: '/pengumuman',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisasiSayaRoute = OrganisasiSayaRouteImport.update({
  id: '/organisasi-saya',
  path: '/organisasi-saya',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifikasiRoute = NotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const MengapaPatunginRoute = MengapaPatunginRouteImport.update({
  id: '/mengapa-patungin',
  path: '/mengapa-patungin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const KonfirmasiBayarRoute = KonfirmasiBayarRouteImport.update({
  id: '/konfirmasi-bayar',
  path: '/konfirmasi-bayar',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinGrupRoute = JoinGrupRouteImport.update({
  id: '/join-grup',
  path: '/join-grup',
  getParentRoute: () => rootRouteImport,
} as any)
const IurankuRoute = IurankuRouteImport.update({
  id: '/iuranku',
  path: '/iuranku',
  getParentRoute: () => rootRouteImport,
} as any)
const IuranOrganisasiRoute = IuranOrganisasiRouteImport.update({
  id: '/iuran-organisasi',
  path: '/iuran-organisasi',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoGrupRoute = InfoGrupRouteImport.update({
  id: '/info-grup',
  path: '/info-grup',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSayaRoute = EventSayaRouteImport.update({
  id: '/event-saya',
  path: '/event-saya',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaRoute = AnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramKerjaBuatRoute = ProgramKerjaBuatRouteImport.update({
  id: '/program-kerja_/buat',
  path: '/program-kerja/buat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramKerjaProgIdRoute = ProgramKerjaProgIdRouteImport.update({
  id: '/program-kerja_/$progId',
  path: '/program-kerja/$progId',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanCatIdRoute = LaporanCatIdRouteImport.update({
  id: '/laporan_/$catId',
  path: '/laporan/$catId',
  getParentRoute: () => rootRouteImport,
} as any)
const IuranOrganisasiIuranIdRoute = IuranOrganisasiIuranIdRouteImport.update({
  id: '/iuran-organisasi_/$iuranId',
  path: '/iuran-organisasi/$iuranId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event_/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
  '/event-saya': typeof EventSayaRoute
  '/home': typeof HomeRoute
  '/info-grup': typeof InfoGrupRoute
  '/iuran-organisasi': typeof IuranOrganisasiRoute
  '/iuranku': typeof IurankuRoute
  '/join-grup': typeof JoinGrupRoute
  '/konfirmasi-bayar': typeof KonfirmasiBayarRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/mengapa-patungin': typeof MengapaPatunginRoute
  '/notifikasi': typeof NotifikasiRoute
  '/organisasi-saya': typeof OrganisasiSayaRoute
  '/pengumuman': typeof PengumumanRoute
  '/pricing': typeof PricingRoute
  '/profil': typeof ProfilRoute
  '/program-kerja': typeof ProgramKerjaRoute
  '/register': typeof RegisterRoute
  '/reminder-demo': typeof ReminderDemoRoute
  '/transaksi': typeof TransaksiRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/iuran-organisasi/$iuranId': typeof IuranOrganisasiIuranIdRoute
  '/laporan/$catId': typeof LaporanCatIdRoute
  '/program-kerja/$progId': typeof ProgramKerjaProgIdRoute
  '/program-kerja/buat': typeof ProgramKerjaBuatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
  '/event-saya': typeof EventSayaRoute
  '/home': typeof HomeRoute
  '/info-grup': typeof InfoGrupRoute
  '/iuran-organisasi': typeof IuranOrganisasiRoute
  '/iuranku': typeof IurankuRoute
  '/join-grup': typeof JoinGrupRoute
  '/konfirmasi-bayar': typeof KonfirmasiBayarRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/mengapa-patungin': typeof MengapaPatunginRoute
  '/notifikasi': typeof NotifikasiRoute
  '/organisasi-saya': typeof OrganisasiSayaRoute
  '/pengumuman': typeof PengumumanRoute
  '/pricing': typeof PricingRoute
  '/profil': typeof ProfilRoute
  '/program-kerja': typeof ProgramKerjaRoute
  '/register': typeof RegisterRoute
  '/reminder-demo': typeof ReminderDemoRoute
  '/transaksi': typeof TransaksiRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/iuran-organisasi/$iuranId': typeof IuranOrganisasiIuranIdRoute
  '/laporan/$catId': typeof LaporanCatIdRoute
  '/program-kerja/$progId': typeof ProgramKerjaProgIdRoute
  '/program-kerja/buat': typeof ProgramKerjaBuatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
  '/event-saya': typeof EventSayaRoute
  '/home': typeof HomeRoute
  '/info-grup': typeof InfoGrupRoute
  '/iuran-organisasi': typeof IuranOrganisasiRoute
  '/iuranku': typeof IurankuRoute
  '/join-grup': typeof JoinGrupRoute
  '/konfirmasi-bayar': typeof KonfirmasiBayarRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/mengapa-patungin': typeof MengapaPatunginRoute
  '/notifikasi': typeof NotifikasiRoute
  '/organisasi-saya': typeof OrganisasiSayaRoute
  '/pengumuman': typeof PengumumanRoute
  '/pricing': typeof PricingRoute
  '/profil': typeof ProfilRoute
  '/program-kerja': typeof ProgramKerjaRoute
  '/register': typeof RegisterRoute
  '/reminder-demo': typeof ReminderDemoRoute
  '/transaksi': typeof TransaksiRoute
  '/event_/$eventId': typeof EventEventIdRoute
  '/iuran-organisasi_/$iuranId': typeof IuranOrganisasiIuranIdRoute
  '/laporan_/$catId': typeof LaporanCatIdRoute
  '/program-kerja_/$progId': typeof ProgramKerjaProgIdRoute
  '/program-kerja_/buat': typeof ProgramKerjaBuatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anggota'
    | '/event-saya'
    | '/home'
    | '/info-grup'
    | '/iuran-organisasi'
    | '/iuranku'
    | '/join-grup'
    | '/konfirmasi-bayar'
    | '/laporan'
    | '/login'
    | '/mengapa-patungin'
    | '/notifikasi'
    | '/organisasi-saya'
    | '/pengumuman'
    | '/pricing'
    | '/profil'
    | '/program-kerja'
    | '/register'
    | '/reminder-demo'
    | '/transaksi'
    | '/event/$eventId'
    | '/iuran-organisasi/$iuranId'
    | '/laporan/$catId'
    | '/program-kerja/$progId'
    | '/program-kerja/buat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anggota'
    | '/event-saya'
    | '/home'
    | '/info-grup'
    | '/iuran-organisasi'
    | '/iuranku'
    | '/join-grup'
    | '/konfirmasi-bayar'
    | '/laporan'
    | '/login'
    | '/mengapa-patungin'
    | '/notifikasi'
    | '/organisasi-saya'
    | '/pengumuman'
    | '/pricing'
    | '/profil'
    | '/program-kerja'
    | '/register'
    | '/reminder-demo'
    | '/transaksi'
    | '/event/$eventId'
    | '/iuran-organisasi/$iuranId'
    | '/laporan/$catId'
    | '/program-kerja/$progId'
    | '/program-kerja/buat'
  id:
    | '__root__'
    | '/'
    | '/anggota'
    | '/event-saya'
    | '/home'
    | '/info-grup'
    | '/iuran-organisasi'
    | '/iuranku'
    | '/join-grup'
    | '/konfirmasi-bayar'
    | '/laporan'
    | '/login'
    | '/mengapa-patungin'
    | '/notifikasi'
    | '/organisasi-saya'
    | '/pengumuman'
    | '/pricing'
    | '/profil'
    | '/program-kerja'
    | '/register'
    | '/reminder-demo'
    | '/transaksi'
    | '/event_/$eventId'
    | '/iuran-organisasi_/$iuranId'
    | '/laporan_/$catId'
    | '/program-kerja_/$progId'
    | '/program-kerja_/buat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnggotaRoute: typeof AnggotaRoute
  EventSayaRoute: typeof EventSayaRoute
  HomeRoute: typeof HomeRoute
  InfoGrupRoute: typeof InfoGrupRoute
  IuranOrganisasiRoute: typeof IuranOrganisasiRoute
  IurankuRoute: typeof IurankuRoute
  JoinGrupRoute: typeof JoinGrupRoute
  KonfirmasiBayarRoute: typeof KonfirmasiBayarRoute
  LaporanRoute: typeof LaporanRoute
  LoginRoute: typeof LoginRoute
  MengapaPatunginRoute: typeof MengapaPatunginRoute
  NotifikasiRoute: typeof NotifikasiRoute
  OrganisasiSayaRoute: typeof OrganisasiSayaRoute
  PengumumanRoute: typeof PengumumanRoute
  PricingRoute: typeof PricingRoute
  ProfilRoute: typeof ProfilRoute
  ProgramKerjaRoute: typeof ProgramKerjaRoute
  RegisterRoute: typeof RegisterRoute
  ReminderDemoRoute: typeof ReminderDemoRoute
  TransaksiRoute: typeof TransaksiRoute
  EventEventIdRoute: typeof EventEventIdRoute
  IuranOrganisasiIuranIdRoute: typeof IuranOrganisasiIuranIdRoute
  LaporanCatIdRoute: typeof LaporanCatIdRoute
  ProgramKerjaProgIdRoute: typeof ProgramKerjaProgIdRoute
  ProgramKerjaBuatRoute: typeof ProgramKerjaBuatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transaksi': {
      id: '/transaksi'
      path: '/transaksi'
      fullPath: '/transaksi'
      preLoaderRoute: typeof TransaksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder-demo': {
      id: '/reminder-demo'
      path: '/reminder-demo'
      fullPath: '/reminder-demo'
      preLoaderRoute: typeof ReminderDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-kerja': {
      id: '/program-kerja'
      path: '/program-kerja'
      fullPath: '/program-kerja'
      preLoaderRoute: typeof ProgramKerjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengumuman': {
      id: '/pengumuman'
      path: '/pengumuman'
      fullPath: '/pengumuman'
      preLoaderRoute: typeof PengumumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisasi-saya': {
      id: '/organisasi-saya'
      path: '/organisasi-saya'
      fullPath: '/organisasi-saya'
      preLoaderRoute: typeof OrganisasiSayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifikasi': {
      id: '/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof NotifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mengapa-patungin': {
      id: '/mengapa-patungin'
      path: '/mengapa-patungin'
      fullPath: '/mengapa-patungin'
      preLoaderRoute: typeof MengapaPatunginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konfirmasi-bayar': {
      id: '/konfirmasi-bayar'
      path: '/konfirmasi-bayar'
      fullPath: '/konfirmasi-bayar'
      preLoaderRoute: typeof KonfirmasiBayarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-grup': {
      id: '/join-grup'
      path: '/join-grup'
      fullPath: '/join-grup'
      preLoaderRoute: typeof JoinGrupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iuranku': {
      id: '/iuranku'
      path: '/iuranku'
      fullPath: '/iuranku'
      preLoaderRoute: typeof IurankuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iuran-organisasi': {
      id: '/iuran-organisasi'
      path: '/iuran-organisasi'
      fullPath: '/iuran-organisasi'
      preLoaderRoute: typeof IuranOrganisasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info-grup': {
      id: '/info-grup'
      path: '/info-grup'
      fullPath: '/info-grup'
      preLoaderRoute: typeof InfoGrupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-saya': {
      id: '/event-saya'
      path: '/event-saya'
      fullPath: '/event-saya'
      preLoaderRoute: typeof EventSayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota': {
      id: '/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof AnggotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-kerja_/buat': {
      id: '/program-kerja_/buat'
      path: '/program-kerja/buat'
      fullPath: '/program-kerja/buat'
      preLoaderRoute: typeof ProgramKerjaBuatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-kerja_/$progId': {
      id: '/program-kerja_/$progId'
      path: '/program-kerja/$progId'
      fullPath: '/program-kerja/$progId'
      preLoaderRoute: typeof ProgramKerjaProgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan_/$catId': {
      id: '/laporan_/$catId'
      path: '/laporan/$catId'
      fullPath: '/laporan/$catId'
      preLoaderRoute: typeof LaporanCatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iuran-organisasi_/$iuranId': {
      id: '/iuran-organisasi_/$iuranId'
      path: '/iuran-organisasi/$iuranId'
      fullPath: '/iuran-organisasi/$iuranId'
      preLoaderRoute: typeof IuranOrganisasiIuranIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event_/$eventId': {
      id: '/event_/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnggotaRoute: AnggotaRoute,
  EventSayaRoute: EventSayaRoute,
  HomeRoute: HomeRoute,
  InfoGrupRoute: InfoGrupRoute,
  IuranOrganisasiRoute: IuranOrganisasiRoute,
  IurankuRoute: IurankuRoute,
  JoinGrupRoute: JoinGrupRoute,
  KonfirmasiBayarRoute: KonfirmasiBayarRoute,
  LaporanRoute: LaporanRoute,
  LoginRoute: LoginRoute,
  MengapaPatunginRoute: MengapaPatunginRoute,
  NotifikasiRoute: NotifikasiRoute,
  OrganisasiSayaRoute: OrganisasiSayaRoute,
  PengumumanRoute: PengumumanRoute,
  PricingRoute: PricingRoute,
  ProfilRoute: ProfilRoute,
  ProgramKerjaRoute: ProgramKerjaRoute,
  RegisterRoute: RegisterRoute,
  ReminderDemoRoute: ReminderDemoRoute,
  TransaksiRoute: TransaksiRoute,
  EventEventIdRoute: EventEventIdRoute,
  IuranOrganisasiIuranIdRoute: IuranOrganisasiIuranIdRoute,
  LaporanCatIdRoute: LaporanCatIdRoute,
  ProgramKerjaProgIdRoute: ProgramKerjaProgIdRoute,
  ProgramKerjaBuatRoute: ProgramKerjaBuatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
